### ISSUE TITLE
[AWS]Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method

### ISSUE THREAD

**Issue by yuniny2** [cloudfoundry-incubator/bosh-aws-cpi-release#84] opened 2018-06-07 02:04 UTC
I deployed using bbl for cf-deploy.
```
bosh cli  version : 3.0.1-712bfd7-2018-03-13T23:26:43Z
director  version : 265.2.0 (00000000)
bbl version : bbl 6.7.1 (linux/amd64)
stemcell version: 3586.8
```

the deploy is as follows.
```
bosh deploy -d cf cf-deployment/cf-deployment.yml \
 --vars-store cf-deployment-vars.yml \
 -o cf-deployment/operations/aws.yml \
 -o cf-deployment/operations/scale-to-one-az.yml \
 -v system_domain=cf-test4.com
```
and then I got the error 

```
Task 39 | 07:23:47 | Preparing deployment: Preparing deployment (00:00:02)
Task 39 | 07:23:52 | Preparing package compilation: Finding packages to compile (00:00:01)
Task 39 | 07:23:53 | Compiling packages: libtool/3e211ee9e3aab09a9e8a9ff55ab9ce9ba81590d945640e2d29c078597db33a94
Task 39 | 07:23:53 | Compiling packages: autoconf/4f8914a0ada02006da32066d2e374e2a065d3acafbceb60ffd45ea146df7af1f
Task 39 | 07:23:53 | Compiling packages: libseccomp/11f3a8e12b881d4d6f660d84df70d3fe99b12e1621f9e93ff66e120aec12ec96
Task 39 | 07:23:53 | Compiling packages: tar/f922f97b27619f8331332e4186c1f9c63fa5b4ddd213c4a02c7ed7cf68fced21
Task 39 | 07:23:53 | Compiling packages: apparmor/0133a2288b0f71d05d89bd117c957297ad19cd19c0253236ba0ce4dedeb27186
Task 39 | 07:23:53 | Compiling packages: busybox/02b86e9e891e78294e366cfc3361514b752308952f56b954f7a6ae31961f859c
Task 39 | 07:24:46 | Compiling packages: autoconf/4f8914a0ada02006da32066d2e374e2a065d3acafbceb60ffd45ea146df7af1f (00:00:53)
                   L Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method
Task 39 | 07:24:46 | Compiling packages: libseccomp/11f3a8e12b881d4d6f660d84df70d3fe99b12e1621f9e93ff66e120aec12ec96 (00:00:53)
                   L Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method
Task 39 | 07:24:46 | Compiling packages: busybox/02b86e9e891e78294e366cfc3361514b752308952f56b954f7a6ae31961f859c (00:00:53)
                   L Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method
Task 39 | 07:24:47 | Compiling packages: libtool/3e211ee9e3aab09a9e8a9ff55ab9ce9ba81590d945640e2d29c078597db33a94 (00:00:54)
                   L Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method
Task 39 | 07:24:47 | Compiling packages: apparmor/0133a2288b0f71d05d89bd117c957297ad19cd19c0253236ba0ce4dedeb27186 (00:00:54)
                   L Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method
Task 39 | 07:24:47 | Compiling packages: tar/f922f97b27619f8331332e4186c1f9c63fa5b4ddd213c4a02c7ed7cf68fced21 (00:00:54)
                   L Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method
Task 39 | 07:24:47 | Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method

Task 39 Started  Tue Jun  5 07:23:47 UTC 2018
Task 39 Finished Tue Jun  5 07:24:47 UTC 2018
Task 39 Duration 00:01:00
Task 39 error

Updating deployment:
  Expected task '39' to succeed but state is 'error'

Exit code 1
````
What's that mean ? 
Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method

**Comment by pmarkham** [comment] 2018-07-30 23:28
I hit this issue as well when trying to install Cloud Foundry. I have BOSH client version 5.0.1-2432e5e9-2018-07-18T21:41:06Z and cloned the repositories for BBL and cf-deployment.

It looks like the error was happening trying to create the compilation VMs.

Here's the Cloud Trail log:

```
        {
            "awsRegion": "ap-southeast-2",
            "errorCode": "Client.InvalidBlockDeviceMapping",
            "errorMessage": "snapshotId can only be modified on EBS devices",
            "eventID": "d0ff7f17-15b0-4635-9de2-5e2dcd5c76bc",
            "eventName": "RunInstances",
            "eventSource": "ec2.amazonaws.com",
            "eventTime": "2018-07-24T00:21:13Z",
            "eventType": "AwsApiCall",
            "eventVersion": "1.05",
            "recipientAccountId": "XXXXXXXXXXX",
            "requestID": "d40e4c17-3f43-404e-8ab9-04cd0bf7d019",
            "requestParameters": {
                "availabilityZone": "ap-southeast-2a",
                "blockDeviceMapping": {
                    "items": [
                        {
                            "deviceName": "/dev/sdb",
                            "ebs": {
                                "deleteOnTermination": true,
                                "snapshotId": "snap-0b5a30e878aa4fb4e",
                                "volumeSize": 10,
                                "volumeType": "gp2"
                            }
                        },
                        {
                            "deviceName": "/dev/xvda",
                            "ebs": {
                                "deleteOnTermination": true,
                                "volumeType": "gp2"
                            }
                        }
                    ]
                },
                "disableApiTermination": false,
                "instanceType": "m4.xlarge",
                "instancesSet": {
                    "items": [
                        {
                            "imageId": "ami-0d49173c3ceaad5bc",
                            "keyName": "bbl-env-turkana-2018-07-20t01-06z_bosh_vms",
                            "maxCount": 1,
                            "minCount": 1
                        }
                    ]
                },
                "monitoring": {
                    "enabled": false
                },
                "networkInterfaceSet": {
                    "items": [
                        {
                            "deviceIndex": 0,
                            "groupSet": {
                                "items": [
                                    {
                                        "groupId": "sg-0b20fc41652c55e01"
                                    }
                                ]
                            },
                            "privateIpAddress": "10.0.16.7",
                            "subnetId": "subnet-089a727638f71330a"
                        }
                    ]
                },
                "userData": "<sensitiveDataRemoved>"
            },
            "responseElements": null,
            "sourceIPAddress": "54.206.123.2",
            "userAgent": "aws-sdk-ruby2/2.10.71 ruby/2.4.4 x86_64-linux",
            "userIdentity": {
                "accessKeyId": "XXXXXXXXXXXXXXXXXXXX",
                "accountId": "XXXXXXXXXXXX",
                "arn": "arn:aws:sts::XXXXXXXXXXXX:assumed-role/bbl-env-turkana-2018-07-20t01-06z_bosh_role/i-0cd9cce07a2dcce43",
                "principalId": "XXXXXXXXXXXXXXXXXXXX:i-0cd9cce07a2dcce43",
                "sessionContext": {
                    "attributes": {
                        "creationDate": "2018-07-24T00:20:12Z",
                        "mfaAuthenticated": "false"
                    },
                    "sessionIssuer": {
                        "accountId": "XXXXXXXXXXXX",
                        "arn": "arn:aws:iam::XXXXXXXXXXXX:role/bbl-env-turkana-2018-07-20t01-06z_bosh_role",
                        "principalId": "XXXXXXXXXXXXXXXXXXXX",
                        "type": "Role",
                        "userName": "bbl-env-turkana-2018-07-20t01-06z_bosh_role"
                    }
                },
                "type": "AssumedRole"
            }
        },
```

A post of Stackoverflow suggests that changing the device name from `/dev/sdb` to `/dev/sd[f-p]` may help: https://stackoverflow.com/questions/24346302/launching-with-snapshot-based-volume-fails

I manually changed the CPI code on my BOSH instance to make the device `/dev/sdf` and this was more successful, eventually getting an error as the Consul server already used this device. I then changed the device to `/dev/sdg` and this went through without any issue, successfully deploying Cloud Foundry.

The two files I ended up changing (sorry, don't have a diff) are:

```
/var/vcap/data/packages/bosh_aws_cpi/51e90bdc1c72ee55e17ad908e60d89afe2b7eacf/lib/cloud/aws/block_device_manager.rb:3:    DEFAULT_INSTANCE_STORAGE_DISK_MAPPING = { device_name: '/dev/sdg', virtual_name: 'ephemeral0' }.freeze

/var/vcap/data/packages/bosh_aws_cpi/51e90bdc1c72ee55e17ad908e60d89afe2b7eacf/lib/cloud/aws/volume_properties.rb:34:        { device_name: '/dev/sdg', ebs: mapping }
```

I'm not sure which of these fixed the issue. It looks like the line number in `volume_properties.rb` doesn't match the current version, so an older revision of the CPI may be getting installed by BBL?

**Comment by Nelkyr** [comment] 2018-08-01 15:13
Same issue for me, using the latest Bosh CLi, bbl, terraform, cf-deploy, and following official documentation  
( https://docs.cloudfoundry.org/deploying/common/aws.html and https://docs.cloudfoundry.org/deploying/cf-deployment/deploy-cf.html ) always ends up in this error.

```
Task 31 | 14:29:58 | Preparing deployment: Preparing deployment (00:00:04)
Task 31 | 14:30:12 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 31 | 14:30:12 | Compiling packages: proxy/46e626249d0bf4c3e9904191b303bcd5a35432cdf28aad9761eb4d10576aafac
Task 31 | 14:30:12 | Compiling packages: libtool/3e211ee9e3aab09a9e8a9ff55ab9ce9ba81590d945640e2d29c078597db33a94
Task 31 | 14:30:12 | Compiling packages: autoconf/4f8914a0ada02006da32066d2e374e2a065d3acafbceb60ffd45ea146df7af1f
Task 31 | 14:30:12 | Compiling packages: tar/f922f97b27619f8331332e4186c1f9c63fa5b4ddd213c4a02c7ed7cf68fced21
Task 31 | 14:30:12 | Compiling packages: apparmor/0133a2288b0f71d05d89bd117c957297ad19cd19c0253236ba0ce4dedeb27186
Task 31 | 14:30:12 | Compiling packages: busybox/02b86e9e891e78294e366cfc3361514b752308952f56b954f7a6ae31961f859c
Task 31 | 14:30:51 | Compiling packages: libtool/3e211ee9e3aab09a9e8a9ff55ab9ce9ba81590d945640e2d29c078597db33a94 (00:00:39)
                   L Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method
Task 31 | 14:30:51 | Compiling packages: busybox/02b86e9e891e78294e366cfc3361514b752308952f56b954f7a6ae31961f859c (00:00:39)
                   L Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method
Task 31 | 14:30:51 | Compiling packages: proxy/46e626249d0bf4c3e9904191b303bcd5a35432cdf28aad9761eb4d10576aafac (00:00:39)
                   L Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method
Task 31 | 14:30:51 | Compiling packages: apparmor/0133a2288b0f71d05d89bd117c957297ad19cd19c0253236ba0ce4dedeb27186 (00:00:39)
                   L Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method
Task 31 | 14:30:52 | Compiling packages: autoconf/4f8914a0ada02006da32066d2e374e2a065d3acafbceb60ffd45ea146df7af1f (00:00:40)
                   L Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method
Task 31 | 14:30:52 | Compiling packages: tar/f922f97b27619f8331332e4186c1f9c63fa5b4ddd213c4a02c7ed7cf68fced21 (00:00:40)
                   L Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method
Task 31 | 14:30:52 | Error: Unknown CPI error 'Unknown' with message 'snapshotId can only be modified on EBS devices' in 'create_vm' CPI method

Task 31 Started  Wed Aug  1 14:29:58 UTC 2018
Task 31 Finished Wed Aug  1 14:30:52 UTC 2018
Task 31 Duration 00:00:54
Task 31 error

Updating deployment:
  Expected task '31' to succeed but state is 'error'

Exit code 1
```

@dpb587-pivotal the `vm_type` used in my cloud config is `default`, here's the relevant part from the debug
```
I, [2018-08-01T14:59:12.043005 #5720]  INFO -- [req_id cpi-258894]: Launching on demand instance...
D, [2018-08-01T14:59:12.258219 #5720] DEBUG -- [req_id cpi-258894]: [Aws::EC2::Client 400 0.211292 0 retries] run_instances(image_id:"ami-0475621f7150956e6",instance_type:"c4.large",key_name:"bbl-env-winnipeg-2018-08-01t12-47z_bosh_vms",user_data:"eyJyZWdpc3RyeSI6eyJlbmRwb2ludCI6Imh0dHA6Ly9yZWdpc3RyeTp6NWlj\nN2sycG14OXU0dnczeHdheEAxMC4wLjAuNjoyNTc3NyJ9fQ==",block_device_mappings:[{device_name:"/dev/sdb",ebs:{volume_size:100,volume_type:"gp2",delete_on_termination:true,snapshot_id:"snap-030aab09d9601bd5a"}},{device_name:"/dev/xvda",ebs:{volume_type:"gp2",delete_on_termination:true}}],placement:{availability_zone:"eu-west-1a"},network_interfaces:[{groups:["sg-0f9c78d3aaa2d5b20"],subnet_id:"subnet-093a327778f85b4d8",private_ip_address:"10.0.16.22",device_index:0}],min_count:1,max_count:1) Aws::EC2::Errors::InvalidBlockDeviceMapping snapshotId can only be modified on EBS devices
```

**Comment by yuniny2** [comment] 2018-08-02 02:48
Thank you for your reply

I checked this issue by below git url.

- volume_properties.rb
https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/src/bosh_aws_cpi/lib/cloud/aws/volume_properties.rb#L30

- block_device_manager.rb
https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/src/bosh_aws_cpi/lib/cloud/aws/block_device_manager.rb#L3

**Comment by pmarkham** [comment] 2018-08-14 03:35
@yuniny2, did you mean to close this issue? As far as I can tell, it hasn't been fixed yet.

**Comment by yuniny2** [comment] 2018-08-14 04:40
Hi~ pmarkham

Yes, I know, I'm trying to do the way that you did.
 but in my case  I was faild.

If you want to reopen I will do that~
I hope to fix this case.....

**Comment by yuniny2** [comment] 2018-08-14 07:11
@pmarkham , I've just deployed [**cf-deploy**]  I refer to your comment(modify source in director(bosh/0)).

But, i faced another error.  
```
ubuntu@ip-10-0-1-164:~$ cf api
No api endpoint set. Use 'cf api' to set an endpoint
```
Have you seen this error?

cf-deploy was succeeded.
```
{"time":1534226570,"stage":"Updating instance","tags":["tcp-router"],"total":1,"task":"tcp-router/bf700198-f14e-450c-8347-43c676bf92ba (0) (canary)","index":1,"state":"finished","progress":100}
{"time":1534226570,"stage":"Updating instance","tags":["scheduler"],"total":1,"task":"scheduler/f137f31f-63d3-4b9c-af31-dab2b59343ed (0) (canary)","index":1,"state":"started","progress":0}
{"time":1534226632,"stage":"Updating instance","tags":["scheduler"],"total":1,"task":"scheduler/f137f31f-63d3-4b9c-af31-dab2b59343ed (0) (canary)","index":1,"state":"finished","progress":100}
{"time":1534226632,"stage":"Updating instance","tags":["diego-cell"],"total":1,"task":"diego-cell/9f40638b-ed11-4c24-8e91-c326a9d18f2d (0) (canary)","index":1,"state":"started","progress":0}
{"time":1534226632,"stage":"Updating instance","tags":["doppler"],"total":1,"task":"doppler/6c998a02-37cc-4322-b63b-d6760b94e698 (0) (canary)","index":1,"state":"started","progress":0}
{"time":1534226684,"stage":"Updating instance","tags":["doppler"],"total":1,"task":"doppler/6c998a02-37cc-4322-b63b-d6760b94e698 (0) (canary)","index":1,"state":"finished","progress":100}
{"time":1534226711,"stage":"Updating instance","tags":["diego-cell"],"total":1,"task":"diego-cell/9f40638b-ed11-4c24-8e91-c326a9d18f2d (0) (canary)","index":1,"state":"finished","progress":100}
{"time":1534226711,"stage":"Updating instance","tags":["log-api"],"total":1,"task":"log-api/9ac72f66-ae6f-4da7-a531-4964dada908a (0) (canary)","index":1,"state":"started","progress":0}
{"time":1534226761,"stage":"Updating instance","tags":["log-api"],"total":1,"task":"log-api/9ac72f66-ae6f-4da7-a531-4964dada908a (0) (canary)","index":1,"state":"finished","progress":100}
', "result_output" = '', "context_id" = '' WHERE ("id" = 31)
D, [2018-08-14T06:06:02.012461 #1960] [task:31] DEBUG -- DirectorJobRunner: (0.000947s) (conn: 70055352825620) COMMIT
I, [2018-08-14T06:06:02.012601 #1960] []  INFO -- DirectorJobRunner: Task took 1 hour 26 minutes 16.542125338000005 seconds to process.

Task 31 done

Succeeded
```

**Comment by pmarkham** [comment] 2018-08-14 09:11
@yuniny2, yes, you need to use the `cf api` command to set the API URL that you want to talk to. So do something like:

```cf api https://api.cf-test.com``` then login with ```cf login```

You can combine them with ```cf login -a https://api.cf-test.com```

**Comment by jaresty** [comment] 2018-08-27 20:43
We were able to reproduce this bug in v71 of the aws CPI.  Updating to the latest cpi (v72 as of now) resolved the problem for us.  We're closing this for now; feel free to reopen if you still see a problem after updating to v72.

**Closed by jaresty** 2018-08-27 20:43 UTC
Labels: unscheduled

**Comment by dpb587-pivotal** [comment] 2018-08-28 00:09
cc @evanfarrar; fyi, bosh-deployment was recently bumped to `aws-cpi/72`

**Comment by pmarkham** [comment] 2018-08-28 04:14
It's working for me now, thanks guys.

**Comment by yuniny2** [comment] 2018-08-30 02:48
@pmarkham 
Hi,
It's working for me too. 
But I face with another error... 
Do you know below error ?
```
ubuntu@ip-10-0-0-37:~$ cf api api.cf-cloud5.com
Setting api endpoint to api.cf-cloud5.com...
Request error: Get https://api.cf-cloud5.com/v2/info: dial tcp: lookup api.cf-cloud5.com on 10.0.0.2:53: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
```
Thank you again for your advise, it is greatly appreciated.

**Comment by pmarkham** [comment] 2018-08-30 03:11
@yuniny2, I haven't hit that error, but it's trying to connect to port 53, which is the DNS port. Did you configure BOSH DNS with:

```
bosh update-runtime-config bosh-deployment/runtime-configs/dns.yml --name dns
```

**Comment by vanjan** [comment] 2018-08-30 12:48
how can I update the cpi config?

**Comment by luan** [comment] 2018-08-30 20:59
@vanjan if you're using bosh-deployment this ops file: https://github.com/cloudfoundry/bosh-deployment/blob/master/aws/cpi.yml already has v72. Should work out of the box if you go to latest bosh-deployment.

**Comment by pmarkham** [comment] 2018-08-30 21:39
@vanjan, I just installed that latest version of bbl, which uses the fixed version of the CPI.

**Comment by vanjan** [comment] 2018-08-31 07:07
ok, my Director was deployed using older bbl, so I downloaded the latest version and issued `bbl up` which didn't do anything. I then issues `bbl down` and then `bbl up` again. This worked but I'm sure there's a better way to just update the CPI in an existing bbl deployment.
